{
 "title": "Network Observability Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "SrcNamespace", "label": "Source namespace", "query": ".*" },
   { "name": "DstNamespace", "label": "Dest namespace", "query": ".*" },
   { "name": "SrcWorkload", "label": "Source workload", "query": ".*" },
   { "name": "DstWorkload", "label": "Dest workload", "query": ".*" }
  ]
 },
 "panels": [
  {
   "title": "Flows",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Total flows",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum ( rate({ app=\"netobserv-flowcollector\",SrcK8S_Namespace=~\"$SrcNamespace\",DstK8S_Namespace=~\"$DstNamespace\" }[1m]))"
    }
   ]
  },
  {
   "title": "Flows by source namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(SrcK8S_Namespace) ( rate({ app=\"netobserv-flowcollector\",SrcK8S_Namespace=~\"$SrcNamespace\",DstK8S_Namespace=~\"$DstNamespace\" }[1m]))"
    }
   ]
  },
  {
   "title": "Flows by destination namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(DstK8S_Namespace) ( rate({ app=\"netobserv-flowcollector\",SrcK8S_Namespace=~\"$SrcNamespace\",DstK8S_Namespace=~\"$DstNamespace\" }[1m]))"
    }
   ]
  },
  { "title": "Volumetry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Volumetry by source namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(SrcK8S_Namespace) ( rate({ app=\"netobserv-flowcollector\",SrcK8S_Namespace=~\"$SrcNamespace\",DstK8S_Namespace=~\"$DstNamespace\" } | json | __error__=\"\" | unwrap Bytes [1m]))"
    }
   ]
  },
  {
   "title": "Volumetry by destination namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(DstK8S_Namespace) ( rate({ app=\"netobserv-flowcollector\",SrcK8S_Namespace=~\"$SrcNamespace\",DstK8S_Namespace=~\"$DstNamespace\" } | json | __error__=\"\" | unwrap Bytes [1m]))"
    }
   ]
  },
  {
   "title": "Volumetry by source workload",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(SrcK8S_Namespace,SrcK8S_OwnerName) ( rate({ app=\"netobserv-flowcollector\",SrcK8S_Namespace=~\"$SrcNamespace\",DstK8S_Namespace=~\"$DstNamespace\",SrcK8S_OwnerName=~\"$SrcWorkload\",DstK8S_OwnerName=~\"$DstWorkload\" } | json | __error__=\"\" | unwrap Bytes [1m]))"
    }
   ]
  },
  {
   "title": "Volumetry by destination workload",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(DstK8S_Namespace,DstK8S_OwnerName) ( rate({ app=\"netobserv-flowcollector\",SrcK8S_Namespace=~\"$SrcNamespace\",DstK8S_Namespace=~\"$DstNamespace\",SrcK8S_OwnerName=~\"$SrcWorkload\",DstK8S_OwnerName=~\"$DstWorkload\" } | json | __error__=\"\" | unwrap Bytes [1m]))"
    }
   ]
  },
  { "title": "IPFIX logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "{app=\"netobserv-flowcollector\"}"
    }
   ]
  }
 ]
}