apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-and-deploy-signed
  namespace: demo-sign
  labels:
    tekton.dev/pipeline: build-and-deploy-signed
spec:
  params:
    - name: deployment-name
      value: pipelines-vote-api
    - name: git-url
      value: 'https://github.com/openshift/pipelines-vote-api.git'
    - name: git-revision
      value: master
    - name: IMAGE
      value: 'quay.io/rcarrata/pipelines-vote-api:v2'
    - name: namespace
      value: demo-sign
  pipelineRef:
    name: build-and-deploy-signed
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: source-pvc
